apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-api-deployment
  labels:
    app: exp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp-api
  template:
    metadata:
      labels:
        app: exp-api
    spec:
      containers:
      - name: exp-api
        image: localhost:32000/exp-api:local
        ports:
        - containerPort: 3000
        env:
        - name: POKE
          value: "Pikachu"
---
apiVersion: v1
kind: Service
metadata:
  name: exp-api-service
spec:
  type: NodePort
  selector:
    app: exp-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001